### ISSUE TITLE
Asking for admin on 10.12

### ISSUE THREAD

**Issue by arubdesu** [sillywilly42/reorderwifi#1]
Getting a prompt for admin auth when trying to reorder or remove networks on 10.12 and 10.12.1 beta (16B2333a). Not sure if this being a cached AD account makes a difference, please let me know what other diagnostic information I can provide.
<img width="443" alt="screenshot 2016-09-29 12 44 32" src="https://cloud.githubusercontent.com/assets/388808/18963424/f30de040-8642-11e6-81dc-a00195c5892a.png">

**Comment by sillywilly42** [comment]
Hey Allister, are you running the app as root? I can't reproduce that problem on 10.12 if I run ReorderWiFi.app/Contents/MacOS/ReorderWiFi as root, but I do get the message if I just run it as a standard user. The idea was to pop the app in Casper's Self-Service which would run it with escalated privileges.

I know it's frowned upon to run GUI apps as root but it was a quick fix to an annoying problem for us when I worked at the BBC. I considered talking XPC to a privileged helper tool to avoid running the GUI as root, but it seemed like overkill. I would be willing to revisit this if there was demand for it :)

**Comment by arubdesu** [comment]
😅reading is fundamental, huh? Pardon me, this can finally be the OnDemand task in Munki I was waiting for! Thanks
