### ISSUE TITLE
holds focus when command-tab/click into other running apps

### ISSUE THREAD

**Issue by arubdesu** [sillywilly42/reorderwifi#2]
Is there a reason it holds focus and can't minimize? I understand this is supposed to be limited/quick interaction, and I don't think it needs menus or more GUI, but it would be nice if it behaved normally if it makes sense that end users would keep it open for longer than a little while.

**Comment by sillywilly42** [comment]
The team I worked with when I made this had a very low opinion of our users and assumed they would lose the app and become confused if it didn't stay on top and in the way.

I will change it to behave like a normal app.

**Comment by sillywilly42** [comment]
Fixed in 9f9fa64680d0186e899f446c91f93fddc25ba436
